# Generated by Django 6.1 on 2026-08-19

import django.core.validators
import django.db.models.deletion
import portal.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = []

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='标题')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=150, unique=True, verbose_name='链接别名')),
                ('summary', models.CharField(max_length=240, verbose_name='摘要')),
                ('category', models.CharField(max_length=32, verbose_name='分类')),
                ('body', models.TextField(verbose_name='正文')),
                ('cover', models.ImageField(upload_to=portal.models.news_upload_to, validators=[portal.models.validate_image], verbose_name='封面图')),
                ('image_focus', models.CharField(choices=[('center', '居中'), ('top', '顶部'), ('bottom', '底部'), ('left', '左侧'), ('right', '右侧')], default='center', max_length=10, verbose_name='图片焦点')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('scheduled', '定时发布'), ('offline', '已下线')], default='draft', max_length=12, verbose_name='状态')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='置顶')),
                ('is_featured', models.BooleanField(default=False, verbose_name='首页推荐')),
                ('external_url', models.URLField(blank=True, verbose_name='原文链接')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('is_trashed', models.BooleanField(default=False, verbose_name='已移入回收站')),
                ('view_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='总浏览量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={'verbose_name': '战队资讯', 'verbose_name_plural': '战队资讯', 'ordering': ('-is_pinned', '-published_at', '-created_at')},
        ),
        migrations.CreateModel(
            name='RecruitmentApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_no', models.CharField(editable=False, max_length=20, unique=True, verbose_name='报名编号')),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('contact', models.CharField(max_length=80, verbose_name='联系方式')),
                ('college', models.CharField(max_length=80, verbose_name='学院')),
                ('major', models.CharField(max_length=80, verbose_name='专业')),
                ('grade', models.CharField(max_length=32, verbose_name='年级')),
                ('intended_groups', models.JSONField(verbose_name='意向组别')),
                ('introduction', models.TextField(verbose_name='自我介绍')),
                ('experience', models.TextField(blank=True, verbose_name='项目/竞赛经历')),
                ('availability', models.CharField(max_length=80, verbose_name='每周可投入时间')),
                ('resume', models.FileField(upload_to=portal.models.resume_upload_to, validators=[django.core.validators.FileExtensionValidator(['pdf']), portal.models.validate_resume], verbose_name='PDF 简历')),
                ('consent', models.BooleanField(verbose_name='已同意个人信息使用')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('screened', '初筛通过'), ('interview', '待面试'), ('accepted', '已录取'), ('rejected', '未通过'), ('talent_pool', '人才库')], default='pending', max_length=16, verbose_name='审核状态')),
                ('internal_note', models.TextField(blank=True, verbose_name='内部备注')),
                ('interview_at', models.DateTimeField(blank=True, null=True, verbose_name='面试时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='报名时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={'verbose_name': '招新报名', 'verbose_name_plural': '招新报名', 'ordering': ('-created_at',)},
        ),
        migrations.CreateModel(
            name='RecruitmentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_open', models.BooleanField(default=False, verbose_name='开放在线报名')),
                ('notice', models.CharField(blank=True, default='招新暂未开放，请关注战队最新资讯。', max_length=240, verbose_name='报名提示')),
            ],
            options={'verbose_name': '招新设置', 'verbose_name_plural': '招新设置'},
        ),
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=portal.models.news_upload_to, validators=[portal.models.validate_image], verbose_name='正文图片')),
                ('caption', models.CharField(blank=True, max_length=160, verbose_name='图片说明')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='排序')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='portal.newsarticle', verbose_name='所属资讯')),
            ],
            options={'verbose_name': '正文图片', 'verbose_name_plural': '正文图片', 'ordering': ('sort_order', 'id')},
        ),
        migrations.CreateModel(
            name='NewsRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot', models.JSONField(verbose_name='内容快照')),
                ('note', models.CharField(default='保存修改', max_length=80, verbose_name='操作说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='portal.newsarticle', verbose_name='资讯')),
            ],
            options={'verbose_name': '资讯修改记录', 'verbose_name_plural': '资讯修改记录', 'ordering': ('-created_at',)},
        ),
        migrations.CreateModel(
            name='NewsView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='portal.newsarticle')),
            ],
            options={'indexes': [models.Index(fields=['article', 'created_at'], name='portal_news_article_9132cb_idx')]},
        ),
    ]
