# Generated by Django 6.1 on 2026-08-19

import django.db.models.deletion
import portal.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('portal', '0001_initial')]
    operations = [
        migrations.CreateModel(
            name='NewsCoverSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=portal.models.news_upload_to, validators=[portal.models.validate_image], verbose_name='轮播封面')),
                ('caption', models.CharField(blank=True, max_length=160, verbose_name='图片说明')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='排序')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cover_slides', to='portal.newsarticle', verbose_name='所属资讯')),
            ],
            options={'verbose_name': '封面轮播图', 'verbose_name_plural': '封面轮播图', 'ordering': ('sort_order', 'id')},
        ),
    ]
