# Generated by Django 6.1 on 2026-08-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_newscoverslide'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitmentapplication',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='邮箱'),
        ),
        migrations.AddField(
            model_name='recruitmentapplication',
            name='major_class',
            field=models.CharField(default='', max_length=120, verbose_name='专业与班级'),
        ),
        migrations.AddField(
            model_name='recruitmentapplication',
            name='phone',
            field=models.CharField(default='', max_length=32, verbose_name='手机号码'),
        ),
        migrations.AddField(
            model_name='recruitmentapplication',
            name='qq',
            field=models.CharField(default='', max_length=20, verbose_name='QQ'),
        ),
        migrations.AddField(
            model_name='recruitmentapplication',
            name='wechat',
            field=models.CharField(default='', max_length=80, verbose_name='微信'),
        ),
        migrations.AlterField(
            model_name='recruitmentapplication',
            name='contact',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='旧联系方式'),
        ),
        migrations.AlterField(
            model_name='recruitmentapplication',
            name='grade',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='旧年级'),
        ),
        migrations.AlterField(
            model_name='recruitmentapplication',
            name='major',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='旧专业'),
        ),
    ]
