# Generated by Django 6.1 on 2026-08-20 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_newsimage_stable_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='cover_caption',
            field=models.CharField(blank=True, max_length=160, verbose_name='首张封面说明'),
        ),
    ]
