# Generated by Django 6.1 on 2026-08-20 22:30

import django.db.models.deletion
import portal.models
from django.db import migrations, models


def copy_legacy_choices(apps, schema_editor):
    Application = apps.get_model('portal', 'RecruitmentApplication')
    valid = {'mechanical', 'electrical', 'algorithm', 'operations'}
    for application in Application.objects.all():
        choices = [choice for choice in (application.intended_groups or []) if choice in valid]
        if choices:
            application.primary_choice = choices[0]
            application.accepts_adjustment = len(choices) > 1
            application.second_choice = choices[1] if len(choices) > 1 else ''
            application.save(update_fields=['primary_choice', 'accepts_adjustment', 'second_choice'])


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_newsarticle_cover_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitmentapplication',
            name='accepts_adjustment',
            field=models.BooleanField(default=False, verbose_name='服从组别调剂'),
        ),
        migrations.AddField(
            model_name='recruitmentapplication',
            name='primary_choice',
            field=models.CharField(choices=[('mechanical', '机械组'), ('electrical', '电控组'), ('algorithm', '算法组'), ('operations', '运营组')], default='mechanical', max_length=16, verbose_name='第一志愿'),
        ),
        migrations.AddField(
            model_name='recruitmentapplication',
            name='second_choice',
            field=models.CharField(blank=True, choices=[('mechanical', '机械组'), ('electrical', '电控组'), ('algorithm', '算法组'), ('operations', '运营组')], max_length=16, verbose_name='第二志愿'),
        ),
        migrations.CreateModel(
            name='RecruitmentAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=portal.models.recruitment_attachment_upload_to, validators=[portal.models.validate_recruitment_attachment], verbose_name='报名附件')),
                ('original_name', models.CharField(max_length=255, verbose_name='原始文件名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='portal.recruitmentapplication')),
            ],
            options={
                'verbose_name': '报名附件',
                'verbose_name_plural': '报名附件',
            },
        ),
        migrations.RunPython(copy_legacy_choices, migrations.RunPython.noop),
    ]
