# Generated by Django 6.1 on 2026-08-22 08:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_recruitment_choices_and_attachments'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitmentEmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='邮箱')),
                ('code_hash', models.CharField(max_length=128, verbose_name='验证码哈希')),
                ('expires_at', models.DateTimeField(verbose_name='过期时间')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='验证时间')),
                ('last_sent_at', models.DateTimeField(verbose_name='最近发送时间')),
                ('sent_count', models.PositiveSmallIntegerField(default=1, verbose_name='当日发送次数')),
                ('sent_on', models.DateField(default=django.utils.timezone.localdate, verbose_name='发送日期')),
                ('failed_attempts', models.PositiveSmallIntegerField(default=0, verbose_name='错误尝试次数')),
            ],
            options={
                'verbose_name': '招新邮箱验证码',
                'verbose_name_plural': '招新邮箱验证码',
            },
        ),
        migrations.AddField(
            model_name='recruitmentapplication',
            name='email_verified',
            field=models.BooleanField(default=False, editable=False, verbose_name='邮箱已验证'),
        ),
    ]
