# Generated by Django 6.1 on 2026-08-22 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_recruitmentemailverification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitmentapplication',
            name='modification_count',
            field=models.PositiveSmallIntegerField(default=0, editable=False, verbose_name='报名者修改次数'),
        ),
        migrations.CreateModel(
            name='RecruitmentApplicationRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot', models.JSONField(verbose_name='修改前内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='修改时间')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicant_revisions', to='portal.recruitmentapplication')),
            ],
            options={
                'verbose_name': '报名者修改记录',
                'verbose_name_plural': '报名者修改记录',
                'ordering': ('-created_at',),
            },
        ),
    ]
