# Generated by Django 6.1

import django.core.validators
import portal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_recruitmentapplication_modification_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitmentapplication',
            name='introduction',
            field=models.TextField(verbose_name='个人简介'),
        ),
        migrations.AddField(
            model_name='recruitmentapplication',
            name='honors',
            field=models.TextField(default='', verbose_name='个人荣誉'),
        ),
        migrations.AddField(
            model_name='recruitmentapplication',
            name='roles',
            field=models.TextField(default='', verbose_name='任职情况'),
        ),
        migrations.AddField(
            model_name='recruitmentapplication',
            name='technical_foundation',
            field=models.TextField(default='', verbose_name='技术基础'),
        ),
        migrations.AlterField(
            model_name='recruitmentapplication',
            name='resume',
            field=models.FileField(
                blank=True,
                upload_to=portal.models.resume_upload_to,
                validators=[django.core.validators.FileExtensionValidator(['pdf']), portal.models.validate_resume],
                verbose_name='PDF 简历',
            ),
        ),
    ]
