# Generated by Django 6.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_recruitmentapplication_profile_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitmentapplication',
            name='experience',
            field=models.TextField(verbose_name='项目/竞赛经历'),
        ),
    ]
