# Generated by Django 6.1

import portal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_recruitmentapplication_experience_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitmentapplication',
            name='photo',
            field=models.ImageField(
                blank=True,
                upload_to=portal.models.recruitment_photo_upload_to,
                validators=[portal.models.validate_recruitment_photo],
                verbose_name='个人照片',
            ),
        ),
    ]
