# Generated by Django 6.1 on 2026-09-17 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0014_recruitmentapplication_gender_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitmentapplication',
            name='availability',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='每周可投入时间'),
        ),
    ]
