<script setup lang="ts">
import { onMounted, onUnmounted, ref, watch } from 'vue'
import { useRoute } from 'vue-router'
import { api, type NewsDetail } from '../api'
const route = useRoute(); const article = ref<NewsDetail | null>(null); const error = ref('')
const slide = ref(0); let timer: number | undefined
function startCarousel() { window.clearInterval(timer); timer = window.setInterval(() => { if (article.value && article.value.cover_images.length > 1) slide.value = (slide.value + 1) % article.value.cover_images.length }, 5200) }
function pauseCarousel() { window.clearInterval(timer) }
async function load() { article.value=null; slide.value=0; error.value=''; try { const slug=String(route.params.slug); article.value=await api.article(slug); api.countView(slug).then(v=>{if(article.value)article.value.view_count=v.view_count}); startCarousel() } catch { error.value='这篇资讯不存在或暂未发布。' } }
onMounted(load); watch(() => route.params.slug, load)
onUnmounted(() => window.clearInterval(timer))
</script>
<template><div class="page"><div v-if="error" class="container state"><RouterLink to="/news">← 返回资讯</RouterLink><p>{{ error }}</p></div><article v-else-if="article" class="article"><div class="container"><RouterLink to="/news" class="back">← 返回资讯</RouterLink><div class="meta"><span>{{ article.category }}</span><time>{{ article.published_at?.slice(0,10) }}</time><small>{{ article.view_count }} 浏览</small></div><h1>{{ article.title }}</h1><p class="summary">{{ article.summary }}</p></div><div class="hero" @mouseenter="pauseCarousel" @mouseleave="startCarousel"><img v-for="(image,index) in article.cover_images" :key="image.id" :src="image.url" :alt="image.caption || article.title" :class="{active:index===slide}" :style="{objectPosition:article.image_focus}" /><div v-if="article.cover_images.length>1" class="dots"><button v-for="(_,index) in article.cover_images" :key="index" :class="{active:index===slide}" :aria-label="`显示第 ${index+1} 张封面`" @click="slide=index;startCarousel()"></button></div></div><div class="content"><div v-html="article.body"></div><figure v-for="image in article.images" :key="image.id"><img :src="image.url" :alt="image.caption || article.title" /><figcaption v-if="image.caption">{{ image.caption }}</figcaption></figure><a v-if="article.external_url" :href="article.external_url" target="_blank" rel="noopener" class="external">阅读原文 ↗</a><nav class="siblings"><RouterLink v-if="article.previous" :to="`/news/${article.previous.slug}`">← {{ article.previous.title }}</RouterLink><RouterLink v-if="article.next" :to="`/news/${article.next.slug}`">{{ article.next.title }} →</RouterLink></nav></div></article><p v-else class="container state">正在加载资讯…</p></div></template>
<style scoped>
.page{padding:42px 0 150px}.back{display:inline-block;margin-bottom:34px;color:var(--accent);font:700 .8rem var(--mono);letter-spacing:.1em}.meta{display:flex;gap:15px;align-items:center;color:var(--ink-faint);font:.75rem var(--mono)}.meta span{color:var(--accent)}h1{margin-top:18px;max-width:920px;font-size:clamp(2rem,5vw,4rem)}.summary{max-width:720px;margin-top:22px;color:var(--ink-dim);font-size:1.05rem}.hero{position:relative;width:min(1440px,calc(100% - 48px));aspect-ratio:21/9;margin:52px auto 0;border:1px solid var(--line);overflow:hidden}.hero>img{position:absolute;inset:0;width:100%;height:100%;object-fit:cover;opacity:0;transform:scale(1.025);transition:opacity .75s var(--ease),transform 5.2s linear}.hero>img.active{opacity:1;transform:scale(1)}.dots{position:absolute;display:flex;gap:8px;left:24px;bottom:20px}.dots button{width:28px;height:3px;border:0;background:rgba(255,255,255,.45);transition:background .2s,width .2s}.dots button.active{width:48px;background:var(--accent)}figure img{width:100%;height:100%;object-fit:cover}.content{width:min(760px,calc(100% - 48px));margin:52px auto;color:var(--ink-dim);font-size:1rem}.content :deep(h2){color:var(--ink);margin:42px 0 14px}.content :deep(p){margin:16px 0}.content :deep(ul){padding-left:24px;margin:16px 0}.content figure{margin:34px 0}.content figure img{height:auto;display:block;border:1px solid var(--line)}figcaption{margin-top:8px;color:var(--ink-faint);font-size:.82rem}.external{display:inline-block;margin-top:14px;color:var(--accent);font:700 .8rem var(--mono)}.siblings{display:flex;justify-content:space-between;gap:24px;margin-top:70px;padding-top:22px;border-top:1px solid var(--line)}.siblings a{max-width:45%;color:var(--ink-dim);font-size:.85rem}.siblings a:hover{color:var(--accent)}.state{padding-top:100px;color:var(--ink-dim)}.state p{margin-top:20px}@media(max-width:600px){.hero{aspect-ratio:16/9}.siblings{flex-direction:column}.siblings a{max-width:100%}.page{padding-bottom:90px}}
</style>
