<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { api, type NewsItem } from '../api'
import PageHeader from '../components/PageHeader.vue'
import NewsCoverCarousel from '../components/NewsCoverCarousel.vue'

const items = ref<NewsItem[]>([]), categories = ref<string[]>([]), current = ref(''), loading = ref(true), error = ref('')
async function load() { loading.value = true; error.value = ''; try { const q = current.value ? `?category=${encodeURIComponent(current.value)}` : ''; const result = await api.news(q); items.value = result.items; categories.value = result.categories } catch { error.value = '暂时无法获取资讯，请稍后重试。' } finally { loading.value = false } }
onMounted(load)
const display = computed(() => items.value)
</script>
<template>
  <div class="page"><div class="container"><PageHeader eyebrow="02 / 战队资讯" title="最新动态" desc="赛场战报、技术研发、招新与合作动态，第一时间了解 PRIME。" />
    <div class="news-watermark" aria-hidden="true">NEWS</div><div class="filters"><button :class="{ active: !current }" @click="current='';load()">全部</button><button v-for="category in categories" :key="category" :class="{ active: current===category }" @click="current=category;load()">{{ category }}</button></div>
    <p v-if="loading" class="state">正在加载资讯…</p><p v-else-if="error" class="state error">{{ error }}</p><p v-else-if="!display.length" class="state">暂时没有已发布资讯。</p>
    <div v-else class="grid"><RouterLink v-for="article in display" :key="article.slug" :to="`/news/${article.slug}`" class="card"><div class="media"><NewsCoverCarousel :images="article.cover_images" :title="article.title" :image-focus="article.image_focus" /></div><div class="copy"><div><span>{{ article.category }}</span><time>{{ article.published_at?.slice(0,10) }}</time></div><h2>{{ article.title }}</h2><p>{{ article.summary }}</p><b>查看详情 →</b></div></RouterLink></div>
  </div></div>
</template>
<style scoped>
.page{padding-bottom:var(--section-space);position:relative}.news-watermark{position:absolute;top:136px;left:max(var(--page-gutter),calc((100% - var(--maxw))/2));font-family:var(--display);font-size:clamp(7rem,20vw,18rem);line-height:1;color:transparent;-webkit-text-stroke:1px rgba(238,242,249,.055);pointer-events:none}.filters{position:relative;display:flex;gap:10px;flex-wrap:wrap;margin-top:clamp(36px,5vw,56px)}.filters button{min-height:42px;color:var(--ink-dim);background:transparent;border:1px solid var(--line);border-radius:999px;padding:9px 17px;font:700 .76rem var(--mono);white-space:nowrap;transition:color .25s,border-color .25s,background .25s}.filters button.active,.filters button:hover{color:var(--accent);border-color:var(--accent);background:rgba(45,226,166,.055)}.state{margin:48px 0;color:var(--ink-dim)}.error{color:var(--accent-warm)}.grid{position:relative;margin-top:28px;display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:clamp(14px,2vw,20px)}.card{min-width:0;border:1px solid var(--line);border-radius:var(--radius);background:var(--surface);transition:transform .35s var(--ease-expo),border-color .3s;overflow:hidden}.card:hover{transform:translateY(-5px);border-color:var(--accent)}.media{aspect-ratio:16/9;overflow:hidden;border-bottom:1px solid var(--line)}.media img{width:100%;height:100%;object-fit:cover;transition:transform .7s var(--ease-expo)}.card:hover img{transform:scale(1.05)}.copy{padding:clamp(17px,2vw,22px);display:flex;min-height:235px;flex-direction:column;gap:13px}.copy>div{display:flex;justify-content:space-between;gap:14px}.copy span,.copy b{font:700 .7rem var(--mono);letter-spacing:.1em;color:var(--accent)}time{font:.7rem var(--mono);color:var(--ink-faint);white-space:nowrap}h2{font-size:clamp(1.08rem,1.6vw,1.22rem);overflow-wrap:anywhere}.copy p{font-size:.88rem;color:var(--ink-dim);flex:1}.copy b{display:inline-flex;align-items:center;min-height:36px}@media(max-width:900px){.grid{grid-template-columns:repeat(2,minmax(0,1fr))}.copy{min-height:220px}}@media(max-width:680px){.grid{grid-template-columns:1fr}.filters{margin-inline:calc(var(--page-gutter) * -1);padding-inline:var(--page-gutter);overflow-x:auto;flex-wrap:nowrap;scrollbar-width:none;scroll-snap-type:x proximity}.filters::-webkit-scrollbar{display:none}.filters button{min-height:44px;scroll-snap-align:start}.copy{min-height:auto}.copy p{min-height:3.4em}.page{padding-bottom:90px}}@media(hover:none){.card:hover{transform:none}.card:hover img{transform:none}}
</style>
